name: First Workflow
on: workflow_dispatch
jobs:
  greetingjob:
    runs-on: windows-latest
    steps: 
      - name: Print Greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "Good Bye"
